

GET http://localhost:5273/games

###
GET http://localhost:5273/games/6

###
POST http://localhost:5273/games
Content-Type: application/json

{
  "title": "",
  "genre": "Roguelike",
  "price": 29.99,
  "releaseDate": "2024-05-06"
}

###
PUT http://localhost:5273/games/1
Content-Type: application/json

{
   "title": "The Witcher 3: Wild Hunt",
   "genre": "RPG",
   "price": 29.99,
   "releaseDate": "2015-05-19T00:00:00"
}

###
DELETE http://localhost:5273/games/5